apiVersion: apps/v1
kind: Deployment
metadata:
  name: abcallwebpage
  namespace: abcall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abcallwebpage
  template:
    metadata:
      labels:
        app: abcallwebpage
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: abcallwebpage
        image: crabcall.azurecr.io/samples/abcallwebpage:latest
        resources:
          requests:
            cpu: 20m
            memory: 20Mi
          limits:
            cpu: 30m
            memory: 30Mi
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: abcallwebpage
  namespace: abcall
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: abcallwebpage
